### ISSUE TITLE
[Bug] Anime IDs from kitsu catalogs throwing errors

### ISSUE THREAD

**Issue by deathbeam** [aymene69/stremio-jackett#65] opened 2024-02-01 00:17 UTC
Result of id in routes.js:

[ 'kitsu', '46474', '11' ]

E.g the prefix kitsu is not handled (which is what the kitsu catalog addon adds I assume)

You can aso see that the season info is missing there and it only contains episode and kitsu id, currently looks like the routes code always assumes format ID:SEASON:EPISODE

**Comment by aymene69** [comment] 2024-02-01 20:36
Animes are MESSED up with Jackett. Duplicate of #16

**Closed by aymene69** 2024-02-01 20:36 UTC
Labels: bug
